### ISSUE TITLE
Better structure for extracting theater id in show info – in `structure` >> `utils`

### ISSUE THREAD

**Issue by ybressler** [Broadway-Open-Data/Broadway-Open-Data#10]
Not clear when data is stored where the data for theater id is stored.

**Comment by ybressler** [comment]
Located on `line 176` in `get_table()` in `structure_content/utils/get_page_content.py`

**Comment by stanislavlevitt** [comment]
Tried to search for `theatre_id` in`show_info`. Need to figure out if it's being saved incorrectly or not being saved at all.

**Comment by ybressler** [comment]
Fixed!
