### ISSUE TITLE
Get number of intermissions and length of intermissions

### ISSUE THREAD

**Issue by ybressler** [Broadway-Open-Data/Broadway-Open-Data#6]
Intermission in `show info` varies in format.

Need to create a function which will determine:
- the number of intermissions
- length of intermission(s)

**Comment by nikhil-kamat** [comment]
Working on this in `nikhil-data-manipulation`

**Comment by ybressler** [comment]
Consider loading the data into Jupyter notebook and playing around there. Once you have a decent strategy, consider utilizing as a `.py` file which will be easier to productionize -- but will be harder to test and debug.

**Comment by ybressler** [comment]
Completed! I used your approach @nikhil-kamat , but selected regex over the package `word2number `
